In [84]:
import numpy as np
import pandas as pd
import yfinance as yfin
from fredapi import Fred

In [85]:
df = pd.read_parquet("sp500_prices.parquet")
df

,Date,Open,High,Low,Close,Volume,Ticker
0,2001-01-02,32.129270,32.129270,29.259251,30.340168,2261684,A
1,2001-01-02,0.222645,0.228257,0.217968,0.222645,452312000,AAPL
2,2001-01-02,11.261874,11.495887,11.232622,11.261874,5243919,ABT
3,2001-01-02,1.571624,1.571624,1.532003,1.532003,90000,ACGL
4,2001-01-02,29.005323,29.067432,22.235344,23.221338,16813400,ADBE
...,...,...,...,...,...,...,...
3747289,2026-05-19,152.009995,153.695007,150.669998,153.335007,650188,YUM
3747290,2026-05-19,85.250000,86.364998,84.290001,86.089996,923849,ZBH
3747291,2026-05-19,259.640015,259.845001,249.699997,250.520004,477407,ZBRA
3747292,2026-05-19,60.130001,60.470001,59.189999,60.310001,367297,ZION
3747293,2026-05-19,79.849998,80.360001,77.593002,77.889999,3895872,ZTS

In [86]:
df = df.set_index(["Date","Ticker"]).sort_index()
df

                         Open        High         Low       Close     Volume
Date       Ticker
2001-01-02 A        32.129270   32.129270   29.259251   30.340168    2261684
           AAPL      0.222645    0.228257    0.217968    0.222645  452312000
           ABT      11.261874   11.495887   11.232622   11.261874    5243919
           ACGL      1.571624    1.571624    1.532003    1.532003      90000
           ADBE     29.005323   29.067432   22.235344   23.221338   16813400
...                       ...         ...         ...         ...        ...
2026-05-19 YUM     152.009995  153.695007  150.669998  153.335007     650188
           ZBH      85.250000   86.364998   84.290001   86.089996     923849
           ZBRA    259.640015  259.845001  249.699997  250.520004     477407
           ZION     60.130001   60.470001   59.189999   60.310001     367297
           ZTS      79.849998   80.360001   77.593002   77.889999    3895872

[3747294 rows x 5 columns]

In [87]:
df.to_csv("sp500_prices.csv")

In [88]:
fred = Fred(api_key='e46be1fc28833cbace41a97c33bb6e3b')
data = fred.get_series('SP500')
data

2016-05-20    2052.32
2016-05-23    2048.04
2016-05-24    2076.06
2016-05-25    2090.54
2016-05-26    2090.10
               ...
2026-05-12    7400.96
2026-05-13    7444.25
2026-05-14    7501.24
2026-05-15    7408.50
2026-05-18    7403.05
Length: 2607, dtype: float64

In [89]:
CHECK = {
    "jobless_claims":   "ICSA",          # weekly initial claims, SA
    "nonfarm_payrolls": "PAYEMS",        # payrolls level (thousands)
    "payrolls_mom":     "PAYEMS",        # MoM -> derive, see note above
    "ig_spread":        "BAMLC0A0CM",    # ICE BofA US Corporate OAS
    "hy_spread":        "BAMLH0A0HYM2",  # ICE BofA US High Yield OAS
    "usd_index":        "DTWEXBGS",      # Nominal Broad USD Index
}

for name, sid in CHECK.items():
    try:
        s = fred.get_series(sid)
        print(f"{name:18s} {sid:14s} OK    n={len(s):5d}  "
              f"{s.first_valid_index().date()} -> {s.last_valid_index().date()}")
    except Exception as e:
        print(f"{name:18s} {sid:14s} FAIL  {type(e).__name__}: {e}")

jobless_claims     ICSA           OK    n= 3097  1967-01-07 -> 2026-05-09
nonfarm_payrolls   PAYEMS         OK    n= 1048  1939-01-01 -> 2026-04-01
payrolls_mom       PAYEMS         OK    n= 1048  1939-01-01 -> 2026-04-01
ig_spread          BAMLC0A0CM     OK    n=  792  2023-05-22 -> 2026-05-18
hy_spread          BAMLH0A0HYM2   OK    n=  792  2023-05-22 -> 2026-05-18
usd_index          DTWEXBGS       OK    n= 5315  2006-01-02 -> 2026-05-15

In [90]:
# Series to download: {fred_id: output_column_name}
SERIES = {
    # --- interest rates & yield curve ---
    "DGS10":       "yield_10y",          # 10-Year Treasury yield (daily)
    "DGS2":        "yield_2y",           # 2-Year Treasury yield (daily)
    "T10Y2Y":      "yield_curve_10y2y",  # 10Y-2Y spread (daily) — recession signal
    "T10Y3M":      "yield_curve_10y3m",  # 10Y-3M spread (daily) — classic inversion
    "FEDFUNDS":    "fed_funds_rate",      # Effective Fed Funds Rate (monthly)

    # --- credit & risk appetite ---
    "BAMLH0A0HYM2":  "hy_spread",        # High-yield OAS (daily) — risk-off signal
    "BAMLC0A0CM":    "ig_spread",         # Investment-grade OAS (daily)

    # --- volatility & sentiment ---
    "VIXCLS":      "vix",                # CBOE VIX (daily)

    # --- macro cycle ---
    "INDPRO":      "industrial_prod",    # Industrial Production Index (monthly)
    "UNRATE":      "unemployment",       # Unemployment rate (monthly)
    "CPIAUCSL":    "cpi",               # CPI All Urban (monthly)
    "PAYEMS":      "nonfarm_payrolls",   # Nonfarm payrolls (monthly)
    "ICSA":        "jobless_claims",     # Initial jobless claims (weekly)

    # --- commodities & dollar ---
    "DCOILWTICO":  "oil_wti",           # WTI crude oil (daily)
    "DTWEXBGS":    "usd_index",         # Trade-weighted USD (daily)
    "GOLDAMGBD228NLBM": "gold",         # Gold price (daily)
}

START = "2001-01-01"

raw = {}
for series_id, col in SERIES.items():
    try:
        raw[col] = fred.get_series(series_id, observation_start=START)
    except Exception as e:
        print(f"Failed {series_id}: {e}")

fred_df = pd.DataFrame(raw)
fred_df.index = pd.to_datetime(fred_df.index)
fred_df.index.name = "Date"

# Derived features worth having
fred_df["yield_spread_chg"] = fred_df["yield_curve_10y2y"].diff()
fred_df["cpi_yoy"]          = fred_df["cpi"].pct_change(12) * 100
fred_df["indpro_yoy"]       = fred_df["industrial_prod"].pct_change(12) * 100
fred_df["payrolls_mom"]     = fred_df["nonfarm_payrolls"].diff()

# Align to daily trading dates from the price data, forward-filling
# monthly/quarterly releases into each trading day
prices = pd.read_parquet("sp500_prices.parquet")
trading_days = pd.to_datetime(prices["Date"].unique())
trading_days = pd.DatetimeIndex(sorted(trading_days))

fred_daily = fred_df.reindex(trading_days, method="ffill")

fred_daily.to_parquet("fred_factors.parquet", index=True)
print(fred_daily.shape)
fred_daily.tail()

Failed GOLDAMGBD228NLBM: Bad Request.  The series does not exist.
(6382, 19)

,yield_10y,yield_2y,yield_curve_10y2y,yield_curve_10y3m,fed_funds_rate,hy_spread,ig_spread,vix,industrial_prod,unemployment,cpi,nonfarm_payrolls,jobless_claims,oil_wti,usd_index,yield_spread_chg,cpi_yoy,indpro_yoy,payrolls_mom
2026-05-13,4.46,3.98,0.48,0.77,NaN,2.82,0.76,17.87,NaN,NaN,NaN,NaN,NaN,NaN,118.4737,0.02,0.0,0.0,NaN
2026-05-14,4.47,4.00,0.47,0.78,NaN,2.76,0.76,17.26,NaN,NaN,NaN,NaN,NaN,NaN,118.6696,-0.01,0.0,0.0,NaN
2026-05-15,4.59,4.09,0.50,0.90,NaN,2.80,0.75,18.43,NaN,NaN,NaN,NaN,NaN,NaN,119.2825,0.03,0.0,0.0,NaN
2026-05-18,NaN,NaN,0.54,0.93,NaN,2.83,0.75,17.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.04,0.0,0.0,NaN
2026-05-19,NaN,NaN,0.54,0.93,NaN,2.83,0.75,17.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.04,0.0,0.0,NaN

In [91]:
SERIES = {
    # --- interest rates & yield curve ---
    "DGS10":       "yield_10y",          # 10-Year Treasury yield (daily)
    "DGS2":        "yield_2y",           # 2-Year Treasury yield (daily)
    "T10Y2Y":      "yield_curve_10y2y",  # 10Y-2Y spread (daily) — recession signal
    "T10Y3M":      "yield_curve_10y3m",  # 10Y-3M spread (daily) — classic inversion
    "FEDFUNDS":    "fed_funds_rate",      # Effective Fed Funds Rate (monthly)

    # --- credit & risk appetite ---
    "BAMLH0A0HYM2":  "hy_spread",        # High-yield OAS (daily) — risk-off signal
    "BAMLC0A0CM":    "ig_spread",         # Investment-grade OAS (daily)

    # --- volatility & sentiment ---
    "VIXCLS":      "vix",                # CBOE VIX (daily)

    # --- macro cycle ---
    "INDPRO":      "industrial_prod",    # Industrial Production Index (monthly)
    "UNRATE":      "unemployment",       # Unemployment rate (monthly)
    "CPIAUCSL":    "cpi",               # CPI All Urban (monthly)
    "PAYEMS":      "nonfarm_payrolls",   # Nonfarm payrolls (monthly)
    "ICSA":        "jobless_claims",     # Initial jobless claims (weekly)

    # --- commodities & dollar ---
    "DCOILWTICO":  "oil_wti",           # WTI crude oil (daily)
    "DTWEXBGS":    "usd_index",         # Trade-weighted USD (daily)
    "GOLDAMGBD228NLBM": "gold",         # Gold price (daily)
}

def load_fred_pit(series_id, daily_index, transform=None):
    """Fetch a FRED series as POINT-IN-TIME data.

    Each observation is timestamped at its FIRST-RELEASE date
    (realtime_start from ALFRED), so a backtest only ever sees a figure
    on/after the day it was actually published -- no lookahead, no
    fixed-lag guessing. Falls back to plain observation-date indexing
    if the series has no vintage history.

    Returns (aligned_series, is_pit); is_pit is False if it fell back.
    """
    try:
        raw = fred.get_series_all_releases(series_id)      # ALFRED vintages
    except Exception:
        raw = None

    if raw is not None and len(raw) > 0:
        # one row per observation = its FIRST release (earliest realtime_start)
        pit = (raw.sort_values("realtime_start")
                  .groupby("date", as_index=False).first()
                  .sort_values("date")
                  .reset_index(drop=True))
        pit["realtime_start"] = pd.to_datetime(pit["realtime_start"])

        # transform at NATIVE frequency, on observation-ordered values
        val = pit["value"].astype(float)
        if transform == "mom":
            val = val.diff()
        elif transform == "yoy":
            val = val.pct_change(12)

        # timestamp each value on its RELEASE date, not its observation date
        s = pd.Series(val.values, index=pit["realtime_start"].values)
        is_pit = True
    else:
        # no vintage history -> observation-date series (NOT point-in-time)
        s = fred.get_series(series_id)
        s.index = pd.to_datetime(s.index)
        if transform == "mom":
            s = s.diff()
        elif transform == "yoy":
            s = s.pct_change(12)
        is_pit = False

    # collapse same-day releases, then carry last known value onto trading days
    s = s.sort_index()
    s = s[~s.index.duplicated(keep="last")]
    return s.reindex(daily_index, method="ffill"), is_pit


# --------------------- build the point-in-time panel -----------------------
# the trading-day calendar = the unique dates in your price panel
daily_index = df.index.get_level_values("Date").unique().sort_values()          # your trading-day calendar

fred_pit = {}
for series_id, name in SERIES.items():
    try:
        col, is_pit = load_fred_pit(series_id, daily_index)
        fred_pit[name] = col
        tag = "PIT     " if is_pit else "FALLBACK"
        n  = col.notna().sum()
        fv = col.first_valid_index()
        print(f"{name:20s} {series_id:18s} {tag} non-null={n:5d}  "
              f"first={fv.date() if fv is not None else 'NaT'}")
    except Exception as e:
        print(f"{name:20s} {series_id:18s} FAIL  {type(e).__name__}: {e}")

fred_pit_df = pd.DataFrame(fred_pit, index=daily_index)
print(f"\nBuilt fred_pit_df: {fred_pit_df.shape[0]} rows x {fred_pit_df.shape[1]} cols")

yield_10y            DGS10              FALLBACK non-null= 6335  first=2001-01-02
yield_2y             DGS2               FALLBACK non-null= 6335  first=2001-01-02
yield_curve_10y2y    T10Y2Y             FALLBACK non-null= 6335  first=2001-01-02
yield_curve_10y3m    T10Y3M             FALLBACK non-null= 6335  first=2001-01-02
fed_funds_rate       FEDFUNDS           PIT      non-null= 6382  first=2001-01-02
hy_spread            BAMLH0A0HYM2       PIT      non-null=  751  first=2023-05-22
ig_spread            BAMLC0A0CM         PIT      non-null=  751  first=2023-05-22
vix                  VIXCLS             FALLBACK non-null= 6382  first=2001-01-02
industrial_prod      INDPRO             PIT      non-null= 6382  first=2001-01-02
unemployment         UNRATE             PIT      non-null= 6382  first=2001-01-02
cpi                  CPIAUCSL           PIT      non-null= 6382  first=2001-01-02
nonfarm_payrolls     PAYEMS             PIT      non-null= 6382  first=2001-01-02
jobless_claims       ICSA               PIT      non-null= 4271  first=2009-05-28
oil_wti              DCOILWTICO         PIT      non-null= 3774  first=2011-04-06
usd_index            DTWEXBGS           PIT      non-null= 1833  first=2019-02-04
gold                 GOLDAMGBD228NLBM   FAIL  ValueError: Bad Request.  The series does not exist.

Built fred_pit_df: 6382 rows x 15 cols

In [92]:
fred_pit_df.to_parquet("fred_factors.parquet", index=True)

In [93]:
from edgar import *

set_identity("gsundaram1999@gmail.com")

In [94]:
tickers = sorted(df.index.get_level_values("Ticker").unique().tolist())
pd.Series(tickers, name="Ticker").to_csv("tickers_with_data.csv", index=False)
print(f"Saved {len(tickers)} tickers")

Saved 726 tickers

In [95]:
prices = pd.read_parquet("sp500_prices.parquet").set_index(["Date", "Ticker"]).sort_index()
fred   = pd.read_parquet("fred_factors.parquet")

# --- PIT shift ---
# FRED data on day D is assumed available only after market close on D.
# Shifting by 1 row means: the value that was at index D moves to index D+1,
# so the first trading session that can legally use a release is D+1.
fred_pit = fred.shift(1)

# --- join ---
# prices has (Date, Ticker) MultiIndex; fred_pit is indexed by Date alone.
# on="Date" tells pandas to match the Date level of prices' MultiIndex
# against fred_pit's index — every (Date, Ticker) row gets the same
# macro values for that date (already the prior day's release after shift).
df = prices.join(fred_pit, on="Date", how="left")

print(df.shape)
df.head()

(3747294, 20)

                        Open       High        Low      Close     Volume  \
Date       Ticker
2001-01-02 A       32.129270  32.129270  29.259251  30.340168    2261684
           AAPL     0.222645   0.228257   0.217968   0.222645  452312000
           ABT     11.261874  11.495887  11.232622  11.261874    5243919
           ACGL     1.571624   1.571624   1.532003   1.532003      90000
           ADBE    29.005323  29.067432  22.235344  23.221338   16813400

                   yield_10y  yield_2y  yield_curve_10y2y  yield_curve_10y3m  \
Date       Ticker
2001-01-02 A             NaN       NaN                NaN                NaN
           AAPL          NaN       NaN                NaN                NaN
           ABT           NaN       NaN                NaN                NaN
           ACGL          NaN       NaN                NaN                NaN
           ADBE          NaN       NaN                NaN                NaN

                   fed_funds_rate  hy_spread  ig_spread  vix  industrial_prod  \
Date       Ticker
2001-01-02 A                  NaN        NaN        NaN  NaN              NaN
           AAPL               NaN        NaN        NaN  NaN              NaN
           ABT                NaN        NaN        NaN  NaN              NaN
           ACGL               NaN        NaN        NaN  NaN              NaN
           ADBE               NaN        NaN        NaN  NaN              NaN

                   unemployment  cpi  nonfarm_payrolls  jobless_claims  \
Date       Ticker
2001-01-02 A                NaN  NaN               NaN             NaN
           AAPL             NaN  NaN               NaN             NaN
           ABT              NaN  NaN               NaN             NaN
           ACGL             NaN  NaN               NaN             NaN
           ADBE             NaN  NaN               NaN             NaN

                   oil_wti  usd_index
Date       Ticker
2001-01-02 A           NaN        NaN
           AAPL        NaN        NaN
           ABT         NaN        NaN
           ACGL        NaN        NaN
           ADBE        NaN        NaN

In [96]:
price_cols = ["Open", "High", "Low", "Close", "Volume"]

# --- overall null counts ---
print("=== Null counts per price column ===")
print(df[price_cols].isnull().sum())
print()

# --- per-ticker row count and null summary ---
ticker_stats = (
    df[price_cols]
    .groupby(level="Ticker")
    .agg(
        rows        = ("Close", "count"),        # non-null close rows
        total_rows  = ("Close", "size"),         # total rows incl. NaN
        first_date  = ("Close", lambda s: s.first_valid_index()[0] if s.first_valid_index() else None),
        last_date   = ("Close", lambda s: s.last_valid_index()[0]  if s.last_valid_index()  else None),
        null_close  = ("Close", lambda s: s.isnull().sum()),
    )
)
ticker_stats["pct_missing"] = (ticker_stats["null_close"] / ticker_stats["total_rows"] * 100).round(2)

print("=== Per-ticker coverage ===")
print(ticker_stats.sort_values("pct_missing", ascending=False).to_string())
print()
print(f"Tickers with >5% missing Close: {(ticker_stats['pct_missing'] > 5).sum()}")
print(f"Tickers with any missing Close: {(ticker_stats['null_close'] > 0).sum()}")

=== Null counts per price column ===
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

=== Per-ticker coverage ===
        rows  total_rows first_date  last_date  null_close  pct_missing
Ticker
A       6382        6382 2001-01-02 2026-05-19           0          0.0
NOC     6382        6382 2001-01-02 2026-05-19           0          0.0
NOW     3491        3491 2012-06-29 2026-05-19           0          0.0
NRG     5651        5651 2003-12-02 2026-05-19           0          0.0
NSC     6382        6382 2001-01-02 2026-05-19           0          0.0
NSM     1610        1610 2012-03-08 2018-07-31           0          0.0
NTAP    6382        6382 2001-01-02 2026-05-19           0          0.0
NTRS    6382        6382 2001-01-02 2026-05-19           0          0.0
NUE     6382        6382 2001-01-02 2026-05-19           0          0.0
NVDA    6382        6382 2001-01-02 2026-05-19           0          0.0
NVR     6382        6382 2001-01-02 2026-05-19           0          0.0
NWL     6382        6382 2001-01-02 2026-05-19           0          0.0
NWS     3249        3249 2013-06-19 2026-05-19           0          0.0
NWSA    3249        3249 2013-06-19 2026-05-19           0          0.0
NXPI    3970        3970 2010-08-06 2026-05-19           0          0.0
NYT     6382        6382 2001-01-02 2026-05-19           0          0.0
O       6382        6382 2001-01-02 2026-05-19           0          0.0
ODFL    6382        6382 2001-01-02 2026-05-19           0          0.0
OGN     1259        1259 2021-05-14 2026-05-19           0          0.0
OI      6382        6382 2001-01-02 2026-05-19           0          0.0
OKE     6382        6382 2001-01-02 2026-05-19           0          0.0
NOV     6382        6382 2001-01-02 2026-05-19           0          0.0
NKTR    6382        6382 2001-01-02 2026-05-19           0          0.0
MSFT    6382        6382 2001-01-02 2026-05-19           0          0.0
NKE     6382        6382 2001-01-02 2026-05-19           0          0.0
MTB     6382        6382 2001-01-02 2026-05-19           0          0.0
MTCH    6382        6382 2001-01-02 2026-05-19           0          0.0
MTD     6382        6382 2001-01-02 2026-05-19           0          0.0
MTG     6382        6382 2001-01-02 2026-05-19           0          0.0
MTW     6382        6382 2001-01-02 2026-05-19           0          0.0
MU      6382        6382 2001-01-02 2026-05-19           0          0.0
MUR     6382        6382 2001-01-02 2026-05-19           0          0.0
NAVI    3040        3040 2014-04-17 2026-05-19           0          0.0
NBR     6382        6382 2001-01-02 2026-05-19           0          0.0
NCC     2342        2342 2012-05-03 2022-03-02           0          0.0
NCLH    3353        3353 2013-01-18 2026-05-19           0          0.0
NDAQ    6010        6010 2002-07-01 2026-05-19           0          0.0
NDSN    6382        6382 2001-01-02 2026-05-19           0          0.0
NE      1242        1242 2021-06-09 2026-05-19           0          0.0
NEE     6382        6382 2001-01-02 2026-05-19           0          0.0
NEM     6382        6382 2001-01-02 2026-05-19           0          0.0
NFLX    6036        6036 2002-05-23 2026-05-19           0          0.0
NFX     4556        4556 2001-01-02 2019-02-13           0          0.0
NI      6382        6382 2001-01-02 2026-05-19           0          0.0
OMC     6382        6382 2001-01-02 2026-05-19           0          0.0
ON      6382        6382 2001-01-02 2026-05-19           0          0.0
ORCL    6382        6382 2001-01-02 2026-05-19           0          0.0
ORLY    6382        6382 2001-01-02 2026-05-19           0          0.0
PLD     6382        6382 2001-01-02 2026-05-19           0          0.0
PLTR    1415        1415 2020-09-30 2026-05-19           0          0.0
PM      4573        4573 2008-03-17 2026-05-19           0          0.0
PNC     6382        6382 2001-01-02 2026-05-19           0          0.0
PNR     6382        6382 2001-01-02 2026-05-19           0          0.0
PNW     6382        6382 2001-01-02 2026-05-19           0          0.0
PODD    4784        4784 2007-05-15 2026-05-19           0          0.0
POM      154         154 2025-10-08 2026-05-19           0          0.0
POOL    6382        6382 2001-01-02 2026-05-19           0          0.0
PPG     6382        6382 2001-01-02 2026-05-19           0          0.0
PPL     6382        6382 2001-01-02 2026-05-19           0          0.0
PRGO    6382        6382 2001-01-02 2026-05-19           0          0.0
PRU     6146        6146 2001-12-13 2026-05-19           0          0.0
PSA     6382        6382 2001-01-02 2026-05-19           0          0.0
PSKY    5145        5145 2005-12-05 2026-05-19           0          0.0
PSX     3546        3546 2012-04-12 2026-05-19           0          0.0
PTC     6382        6382 2001-01-02 2026-05-19           0          0.0
PTV     1602        1602 2010-12-31 2017-05-31           0          0.0
PVH     6382        6382 2001-01-02 2026-05-19           0          0.0
PKG     6382        6382 2001-01-02 2026-05-19           0          0.0
PHM     6382        6382 2001-01-02 2026-05-19           0          0.0
PH      6382        6382 2001-01-02 2026-05-19           0          0.0
PCG     6382        6382 2001-01-02 2026-05-19           0          0.0
OTIS    1550        1550 2020-03-19 2026-05-19           0          0.0
OXY     6382        6382 2001-01-02 2026-05-19           0          0.0
PANW    3477        3477 2012-07-20 2026-05-19           0          0.0
PAYC    3042        3042 2014-04-15 2026-05-19           0          0.0
PAYX    6382        6382 2001-01-02 2026-05-19           0          0.0
PBG     3340        3340 2004-08-03 2020-01-24           0          0.0
PBI     6382        6382 2001-01-02 2026-05-19           0          0.0
PCAR    6382        6382 2001-01-02 2026-05-19           0          0.0
PCL      199         199 2025-08-05 2026-05-19           0          0.0
PGR     6382        6382 2001-01-02 2026-05-19           0          0.0
PCS      201         201 2025-08-01 2026-05-19           0          0.0
PD      1786        1786 2019-04-11 2026-05-19           0          0.0
PEG     6382        6382 2001-01-02 2026-05-19           0          0.0
PENN    6382        6382 2001-01-02 2026-05-19           0          0.0
PEP     6382        6382 2001-01-02 2026-05-19           0          0.0
PFE     6382        6382 2001-01-02 2026-05-19           0          0.0
PFG     6182        6182 2001-10-23 2026-05-19           0          0.0
PG      6382        6382 2001-01-02 2026-05-19           0          0.0
MSI     6382        6382 2001-01-02 2026-05-19           0          0.0
MSCI    4655        4655 2007-11-15 2026-05-19           0          0.0
PWER     619         619 2023-11-29 2026-05-19           0          0.0
KVUE     763         763 2023-05-04 2026-05-19           0          0.0
LB       474         474 2024-06-28 2026-05-19           0          0.0
LDOS    4927        4927 2006-10-17 2026-05-19           0          0.0
LEG     6382        6382 2001-01-02 2026-05-19           0          0.0
LEN     6382        6382 2001-01-02 2026-05-19           0          0.0
LH      6382        6382 2001-01-02 2026-05-19           0          0.0
LHX     6382        6382 2001-01-02 2026-05-19           0          0.0
LIFE      77          77 2026-01-29 2026-05-19           0          0.0
LII     6382        6382 2001-01-02 2026-05-19           0          0.0
LIN     6382        6382 2001-01-02 2026-05-19           0          0.0
LKQ     5691        5691 2003-10-06 2026-05-19           0          0.0
LLY     6382        6382 2001-01-02 2026-05-19           0          0.0
LMT     6382        6382 2001-01-02 2026-05-19           0          0.0
LNC     6382        6382 2001-01-02 2026-05-19           0          0.0
LNT     6382        6382 2001-01-02 2026-05-19           0          0.0
LOW     6382        6382 2001-01-02 2026-05-19           0          0.0
LPX     6382        6382 2001-01-02 2026-05-19           0          0.0
LRCX    6382        6382 2001-01-02 2026-05-19           0          0.0
LU      1393        1393 2020-10-30 2026-05-19           0          0.0
LULU    4733        4733 2007-07-27 2026-05-19           0          0.0
L       6382        6382 2001-01-02 2026-05-19           0          0.0
KSS     6382        6382 2001-01-02 2026-05-19           0          0.0
MS      6382        6382 2001-01-02 2026-05-19           0          0.0
KRI     3232        3232 2006-08-02 2019-06-07           0          0.0
JEF     6382        6382 2001-01-02 2026-05-19           0          0.0
JKHY    6382        6382 2001-01-02 2026-05-19           0          0.0
JNJ     6382        6382 2001-01-02 2026-05-19           0          0.0
JPM     6382        6382 2001-01-02 2026-05-19           0          0.0
KBH     6382        6382 2001-01-02 2026-05-19           0          0.0
KDP     4537        4537 2008-05-07 2026-05-19           0          0.0
KEY     6382        6382 2001-01-02 2026-05-19           0          0.0
KEYS    2912        2912 2014-10-20 2026-05-19           0          0.0
KG      4538        4538 2008-05-06 2026-05-19           0          0.0
KHC     2735        2735 2015-07-06 2026-05-19           0          0.0
KIM     6382        6382 2001-01-02 2026-05-19           0          0.0
KKR     3986        3986 2010-07-15 2026-05-19           0          0.0
KLAC    6382        6382 2001-01-02 2026-05-19           0          0.0
KMB     6382        6382 2001-01-02 2026-05-19           0          0.0
KMG     4496        4496 2001-01-02 2018-11-15           0          0.0
KMI     3839        3839 2011-02-11 2026-05-19           0          0.0
KMX     6382        6382 2001-01-02 2026-05-19           0          0.0
KO      6382        6382 2001-01-02 2026-05-19           0          0.0
KR      6382        6382 2001-01-02 2026-05-19           0          0.0
LUMN    6382        6382 2001-01-02 2026-05-19           0          0.0
LUV     6382        6382 2001-01-02 2026-05-19           0          0.0
LVS     5390        5390 2004-12-15 2026-05-19           0          0.0
LW      2392        2392 2016-11-10 2026-05-19           0          0.0
MGM     6382        6382 2001-01-02 2026-05-19           0          0.0
MHK     6382        6382 2001-01-02 2026-05-19           0          0.0
MHS     1497        1497 2020-02-12 2026-05-18           0          0.0
MI      2634        2634 2015-11-25 2026-05-19           0          0.0
MKC     6382        6382 2001-01-02 2026-05-19           0          0.0
MKTX    5417        5417 2004-11-05 2026-05-19           0          0.0
MLM     6382        6382 2001-01-02 2026-05-19           0          0.0
MMI     3155        3155 2013-10-31 2026-05-19           0          0.0
MMM     6382        6382 2001-01-02 2026-05-19           0          0.0
MNST    6382        6382 2001-01-02 2026-05-19           0          0.0
MO      6382        6382 2001-01-02 2026-05-19           0          0.0
MOH     5757        5757 2003-07-02 2026-05-19           0          0.0
MOLX    3254        3254 2001-01-02 2013-12-09           0          0.0
MOS     6382        6382 2001-01-02 2026-05-19           0          0.0
MPC     3747        3747 2011-06-24 2026-05-19           0          0.0
MPWR    5407        5407 2004-11-19 2026-05-19           0          0.0
MRK     6382        6382 2001-01-02 2026-05-19           0          0.0
MRNA    1871        1871 2018-12-07 2026-05-19           0          0.0
MRSH    6382        6382 2001-01-02 2026-05-19           0          0.0
META    3520        3520 2012-05-18 2026-05-19           0          0.0
MET     6382        6382 2001-01-02 2026-05-19           0          0.0
MER      257         257 2025-05-09 2026-05-18           0          0.0
MAT     6382        6382 2001-01-02 2026-05-19           0          0.0
LYB     4040        4040 2010-04-28 2026-05-19           0          0.0
LYV     5133        5133 2005-12-21 2026-05-19           0          0.0
M       6382        6382 2001-01-02 2026-05-19           0          0.0
MA      5027        5027 2006-05-25 2026-05-19           0          0.0
MAA     6382        6382 2001-01-02 2026-05-19           0          0.0
MAC     6382        6382 2001-01-02 2026-05-19           0          0.0
MAR     6382        6382 2001-01-02 2026-05-19           0          0.0
MAS     6382        6382 2001-01-02 2026-05-19           0          0.0
MAY     2609        2609 2005-09-29 2018-03-14           0          0.0
MEE     2217        2217 2007-08-03 2017-08-10           0          0.0
MBI     6382        6382 2001-01-02 2026-05-19           0          0.0
MCD     6382        6382 2001-01-02 2026-05-19           0          0.0
MCHP    6382        6382 2001-01-02 2026-05-19           0          0.0
MCK     6382        6382 2001-01-02 2026-05-19           0          0.0
MCO     6382        6382 2001-01-02 2026-05-19           0          0.0
MDLZ    6270        6270 2001-06-13 2026-05-19           0          0.0
MDT     6382        6382 2001-01-02 2026-05-19           0          0.0
MEDI     877         877 2022-11-17 2026-05-19           0          0.0
PVN        1           1 2018-10-19 2018-10-19           0          0.0
PWR     6382        6382 2001-01-02 2026-05-19           0          0.0
AAL     5193        5193 2005-09-27 2026-05-19           0          0.0
UAL     5103        5103 2006-02-06 2026-05-19           0          0.0
UCL     1493        1493 2020-06-10 2026-05-19           0          0.0
UDR     6382        6382 2001-01-02 2026-05-19           0          0.0
UHS     6382        6382 2001-01-02 2026-05-19           0          0.0
UIS     6382        6382 2001-01-02 2026-05-19           0          0.0
ULTA    4670        4670 2007-10-25 2026-05-19           0          0.0
UNH     6382        6382 2001-01-02 2026-05-19           0          0.0
UNM     6382        6382 2001-01-02 2026-05-19           0          0.0
UNP     6382        6382 2001-01-02 2026-05-19           0          0.0
UPC     1296        1296 2021-03-23 2026-05-19           0          0.0
UPS     6382        6382 2001-01-02 2026-05-19           0          0.0
URBN    6382        6382 2001-01-02 2026-05-19           0          0.0
URI     6382        6382 2001-01-02 2026-05-19           0          0.0
USB     6382        6382 2001-01-02 2026-05-19           0          0.0
UST     4099        4099 2010-02-02 2026-05-19           0          0.0
UVN     4006        4006 2001-01-02 2018-01-30           0          0.0
V       4571        4571 2008-03-19 2026-05-19           0          0.0
VFC     6382        6382 2001-01-02 2026-05-19           0          0.0
VIAV    6382        6382 2001-01-02 2026-05-19           0          0.0
VICI    2106        2106 2018-01-02 2026-05-19           0          0.0
UBER    1766        1766 2019-05-10 2026-05-19           0          0.0
UAA     5155        5155 2005-11-18 2026-05-19           0          0.0
TLAB    3250        3250 2001-01-02 2013-12-03           0          0.0
UA      2554        2554 2016-03-23 2026-05-19           0          0.0
TMUS    4802        4802 2007-04-19 2026-05-19           0          0.0
TNB     3543        3543 2007-05-02 2022-03-02           0          0.0
TPL     6382        6382 2001-01-02 2026-05-19           0          0.0
TPR     6382        6382 2001-01-02 2026-05-19           0          0.0
TRGP    3885        3885 2010-12-07 2026-05-19           0          0.0
TRIP    3632        3632 2011-12-07 2026-05-19           0          0.0
TRMB    6382        6382 2001-01-02 2026-05-19           0          0.0
TROW    6382        6382 2001-01-02 2026-05-19           0          0.0
TRV     6382        6382 2001-01-02 2026-05-19           0          0.0
TSCO    6382        6382 2001-01-02 2026-05-19           0          0.0
TSLA    3997        3997 2010-06-29 2026-05-19           0          0.0
TSN     6382        6382 2001-01-02 2026-05-19           0          0.0
TT      6382        6382 2001-01-02 2026-05-19           0          0.0
TTD     2428        2428 2016-09-21 2026-05-19           0          0.0
TTWO    6382        6382 2001-01-02 2026-05-19           0          0.0
TWX     4390        4390 2001-01-02 2018-06-15           0          0.0
TXN     6382        6382 2001-01-02 2026-05-19           0          0.0
TXT     6382        6382 2001-01-02 2026-05-19           0          0.0
TYL     6382        6382 2001-01-02 2026-05-19           0          0.0
VLO     6382        6382 2001-01-02 2026-05-19           0          0.0
VLTO     658         658 2023-10-04 2026-05-19           0          0.0
VMC     6382        6382 2001-01-02 2026-05-19           0          0.0
VNO     6382        6382 2001-01-02 2026-05-19           0          0.0
WMT     6382        6382 2001-01-02 2026-05-19           0          0.0
WOR     6382        6382 2001-01-02 2026-05-19           0          0.0
WRB     6382        6382 2001-01-02 2026-05-19           0          0.0
WSM     6382        6382 2001-01-02 2026-05-19           0          0.0
WST     6382        6382 2001-01-02 2026-05-19           0          0.0
WTW     6271        6271 2001-06-12 2026-05-19           0          0.0
WU      4938        4938 2006-10-02 2026-05-19           0          0.0
WY      6382        6382 2001-01-02 2026-05-19           0          0.0
WYNN    5928        5928 2002-10-25 2026-05-19           0          0.0
XEL     6382        6382 2001-01-02 2026-05-19           0          0.0
XOM     6382        6382 2001-01-02 2026-05-19           0          0.0
XRAY    6382        6382 2001-01-02 2026-05-19           0          0.0
XRX     6382        6382 2001-01-02 2026-05-19           0          0.0
XYL     3670        3670 2011-10-13 2026-05-19           0          0.0
XYZ     2638        2638 2015-11-19 2026-05-19           0          0.0
YUM     6382        6382 2001-01-02 2026-05-19           0          0.0
ZBH     6241        6241 2001-07-25 2026-05-19           0          0.0
ZBRA    6382        6382 2001-01-02 2026-05-19           0          0.0
ZION    6382        6382 2001-01-02 2026-05-19           0          0.0
WMB     6382        6382 2001-01-02 2026-05-19           0          0.0
WM      6382        6382 2001-01-02 2026-05-19           0          0.0
WHR     6382        6382 2001-01-02 2026-05-19           0          0.0
VZ      6382        6382 2001-01-02 2026-05-19           0          0.0
VNT     1419        1419 2020-09-24 2026-05-19           0          0.0
VRSK    4179        4179 2009-10-07 2026-05-19           0          0.0
VRSN    6382        6382 2001-01-02 2026-05-19           0          0.0
VRTS    4371        4371 2009-01-02 2026-05-19           0          0.0
VRTX    6382        6382 2001-01-02 2026-05-19           0          0.0
VST     2418        2418 2016-10-05 2026-05-19           0          0.0
VTR     6382        6382 2001-01-02 2026-05-19           0          0.0
VTRS    6382        6382 2001-01-02 2026-05-19           0          0.0
WAB     6382        6382 2001-01-02 2026-05-19           0          0.0
WFC     6382        6382 2001-01-02 2026-05-19           0          0.0
WAT     6382        6382 2001-01-02 2026-05-19           0          0.0
WB      3040        3040 2014-04-17 2026-05-19           0          0.0
WBD     5249        5249 2005-07-08 2026-05-19           0          0.0
WDAY    3418        3418 2012-10-12 2026-05-19           0          0.0
WDC     6382        6382 2001-01-02 2026-05-19           0          0.0
WEC     6382        6382 2001-01-02 2026-05-19           0          0.0
WELL    6382        6382 2001-01-02 2026-05-19           0          0.0
WEN     6382        6382 2001-01-02 2026-05-19           0          0.0
TMO     6382        6382 2001-01-02 2026-05-19           0          0.0
TKO     6382        6382 2001-01-02 2026-05-19           0          0.0
PYPL    2735        2735 2015-07-06 2026-05-19           0          0.0

In [97]:
fred_cols  = [c for c in df.columns if c not in price_cols]

# --- collapse to one row per date (FRED is date-level, not ticker-level) ---
fred_daily_check = df[fred_cols].groupby(level="Date").first()

print(f"Date range: {fred_daily_check.index.min().date()} → {fred_daily_check.index.max().date()}")
print(f"Total trading days: {len(fred_daily_check)}")
print()

# --- null counts and % missing per series ---
stats = pd.DataFrame({
    "non_null":    fred_daily_check.notna().sum(),
    "null":        fred_daily_check.isnull().sum(),
    "pct_missing": (fred_daily_check.isnull().sum() / len(fred_daily_check) * 100).round(2),
    "first_valid": fred_daily_check.apply(lambda s: s.first_valid_index()),
    "last_valid":  fred_daily_check.apply(lambda s: s.last_valid_index()),
})

print("=== FRED series coverage ===")
print(stats.sort_values("pct_missing", ascending=False).to_string())

Date range: 2001-01-02 → 2026-05-19
Total trading days: 6382

=== FRED series coverage ===
                   non_null  null  pct_missing first_valid last_valid
hy_spread               750  5632        88.25  2023-05-23 2026-05-19
ig_spread               750  5632        88.25  2023-05-23 2026-05-19
usd_index              1832  4550        71.29  2019-02-05 2026-05-19
oil_wti                3773  2609        40.88  2011-04-07 2026-05-19
jobless_claims         4270  2112        33.09  2009-05-29 2026-05-19
yield_10y              6334    48         0.75  2001-01-03 2026-05-19
yield_2y               6334    48         0.75  2001-01-03 2026-05-19
yield_curve_10y2y      6334    48         0.75  2001-01-03 2026-05-19
yield_curve_10y3m      6334    48         0.75  2001-01-03 2026-05-19
fed_funds_rate         6381     1         0.02  2001-01-03 2026-05-19
vix                    6381     1         0.02  2001-01-03 2026-05-19
industrial_prod        6381     1         0.02  2001-01-03 2026-05-19
unemployment           6381     1         0.02  2001-01-03 2026-05-19
cpi                    6381     1         0.02  2001-01-03 2026-05-19
nonfarm_payrolls       6381     1         0.02  2001-01-03 2026-05-19

In [98]:
# --- filter to 2005+ ---
df = df[df.index.get_level_values("Date") >= "2005-01-01"]

# --- split column groups ---
price_cols = ["Open", "High", "Low", "Close", "Volume"]
fred_cols  = [c for c in df.columns if c not in price_cols]

# --- fill ---
# FRED: ffill within each column across dates (monthly releases carry forward)
# Price: bfill within each ticker (rare gaps filled from the next available day)
df[fred_cols]  = df[fred_cols].groupby(level="Ticker").ffill()
df[price_cols] = df[price_cols].groupby(level="Ticker").bfill()

print(df.shape)
print(df.isnull().sum())

(3260173, 20)
Open                       0
High                       0
Low                        0
Close                      0
Volume                     0
yield_10y                  0
yield_2y                   0
yield_curve_10y2y          0
yield_curve_10y3m          0
fed_funds_rate             0
hy_spread            2762973
ig_spread            2762973
vix                        0
industrial_prod            0
unemployment               0
cpi                        0
nonfarm_payrolls           0
jobless_claims        590072
oil_wti               854690
usd_index            2067464
dtype: int64

In [99]:
df

                         Open        High         Low       Close     Volume  \
Date       Ticker
2005-01-03 A        14.372443   14.420152   14.014623   14.241242    3378826
           AAP      24.492349   24.625945   24.241859   24.241859    1549500
           AAPL      0.969609    0.974548    0.936979    0.947307  691992000
           ABT      13.617552   13.711264   13.567767   13.667336    7165902
           ACGL      4.067733    4.078298    4.014905    4.025470    1130400
...                       ...         ...         ...         ...        ...
2026-05-19 YUM     152.009995  153.695007  150.669998  153.335007     650188
           ZBH      85.250000   86.364998   84.290001   86.089996     923849
           ZBRA    259.640015  259.845001  249.699997  250.520004     477407
           ZION     60.130001   60.470001   59.189999   60.310001     367297
           ZTS      79.849998   80.360001   77.593002   77.889999    3895872

                   yield_10y  yield_2y  yield_curve_10y2y  yield_curve_10y3m  \
Date       Ticker
2005-01-03 A            4.24      3.08               1.16               2.02
           AAP          4.24      3.08               1.16               2.02
           AAPL         4.24      3.08               1.16               2.02
           ABT          4.24      3.08               1.16               2.02
           ACGL         4.24      3.08               1.16               2.02
...                      ...       ...                ...                ...
2026-05-19 YUM          4.59      4.09               0.54               0.93
           ZBH          4.59      4.09               0.54               0.93
           ZBRA         4.59      4.09               0.54               0.93
           ZION         4.59      4.09               0.54               0.93
           ZTS          4.59      4.09               0.54               0.93

                   fed_funds_rate  hy_spread  ig_spread    vix  \
Date       Ticker
2005-01-03 A                 1.93        NaN        NaN  13.29
           AAP               1.93        NaN        NaN  13.29
           AAPL              1.93        NaN        NaN  13.29
           ABT               1.93        NaN        NaN  13.29
           ACGL              1.93        NaN        NaN  13.29
...                           ...        ...        ...    ...
2026-05-19 YUM               3.64       2.83       0.75  17.82
           ZBH               3.64       2.83       0.75  17.82
           ZBRA              3.64       2.83       0.75  17.82
           ZION              3.64       2.83       0.75  17.82
           ZTS               3.64       2.83       0.75  17.82

                   industrial_prod  unemployment      cpi  nonfarm_payrolls  \
Date       Ticker
2005-01-03 A              117.6000           5.4  191.200          132075.0
           AAP            117.6000           5.4  191.200          132075.0
           AAPL           117.6000           5.4  191.200          132075.0
           ABT            117.6000           5.4  191.200          132075.0
           ACGL           117.6000           5.4  191.200          132075.0
...                            ...           ...      ...               ...
2026-05-19 YUM            102.4963           4.3  332.407          158736.0
           ZBH            102.4963           4.3  332.407          158736.0
           ZBRA           102.4963           4.3  332.407          158736.0
           ZION           102.4963           4.3  332.407          158736.0
           ZTS            102.4963           4.3  332.407          158736.0

                   jobless_claims  oil_wti  usd_index
Date       Ticker
2005-01-03 A                  NaN      NaN        NaN
           AAP                NaN      NaN        NaN
           AAPL               NaN      NaN        NaN
           ABT                NaN      NaN        NaN
           ACGL               NaN      NaN        NaN
...                           ...      ...        ...
2026-05-19 YUM           211000.0   101.56   119.2825
           ZBH           211000.0   101.56   119.2825
           ZBRA          211000.0   101.56   119.2825
           ZION          211000.0   101.56   119.2825
           ZTS           211000.0   101.56   119.2825

[3260173 rows x 20 columns]

In [100]:
EMA_WINDOW = 20  # modifiable — span in trading sessions

# --- forward returns (within each ticker to avoid cross-ticker bleed) ---
df["fwd_ret_5"] = df.groupby(level="Ticker")["Close"].transform(
    lambda s: s.shift(-5) / s - 1
)

# --- valid FRED cols: drop anything missing more than 10% of dates ---
fred_daily = df[fred_cols].groupby(level="Date").first()
fred_daily = df[fred_cols].groupby(level="Date").first()

# keep only numeric columns — datetime cols (e.g. first_valid_index artefacts) break ewm
fred_daily_numeric = fred_daily.select_dtypes(include="number")

valid_fred_cols = fred_daily_numeric.columns[
    fred_daily_numeric.isnull().mean() < 0.10
].tolist()
print(f"Valid FRED cols ({len(valid_fred_cols)}): {valid_fred_cols}")

ema_dev_cols = []
for col in valid_fred_cols:
    dev_col = f"{col}_ema{EMA_WINDOW}_dev"
    fred_daily_numeric[dev_col] = (
        fred_daily_numeric[col]
        - fred_daily_numeric[col].ewm(span=EMA_WINDOW, min_periods=EMA_WINDOW).mean()
    )
    ema_dev_cols.append(dev_col)

for dev_col in ema_dev_cols:
    df[dev_col] = df.index.get_level_values("Date").map(fred_daily_numeric[dev_col])

print(f"\nForward return non-null rows : {df['fwd_ret_5'].notna().sum():,}")
print(f"EMA deviation non-null rows  : {df[ema_dev_cols].notna().all(axis=1).sum():,}")
print(f"\nSample of new columns:")
df[["fwd_ret_5"] + ema_dev_cols].dropna().head()

Valid FRED cols (10): ['yield_10y', 'yield_2y', 'yield_curve_10y2y', 'yield_curve_10y3m', 'fed_funds_rate', 'vix', 'industrial_prod', 'unemployment', 'cpi', 'nonfarm_payrolls']

Forward return non-null rows : 3,256,547
EMA deviation non-null rows  : 3,250,561

Sample of new columns:

                   fwd_ret_5  yield_10y_ema20_dev  yield_2y_ema20_dev  \
Date       Ticker
2005-01-31 A        0.045681            -0.047592            0.022274
           AAP      0.046868            -0.047592            0.022274
           AAPL     0.026528            -0.047592            0.022274
           ABT      0.012661            -0.047592            0.022274
           ACGL     0.078955            -0.047592            0.022274

                   yield_curve_10y2y_ema20_dev  yield_curve_10y3m_ema20_dev  \
Date       Ticker
2005-01-31 A                         -0.069866                    -0.127455
           AAP                       -0.069866                    -0.127455
           AAPL                      -0.069866                    -0.127455
           ABT                       -0.069866                    -0.127455
           ACGL                      -0.069866                    -0.127455

                   fed_funds_rate_ema20_dev  vix_ema20_dev  \
Date       Ticker
2005-01-31 A                       0.003782      -0.243667
           AAP                     0.003782      -0.243667
           AAPL                    0.003782      -0.243667
           ABT                     0.003782      -0.243667
           ACGL                    0.003782      -0.243667

                   industrial_prod_ema20_dev  unemployment_ema20_dev  \
Date       Ticker
2005-01-31 A                         0.05725                     0.0
           AAP                       0.05725                     0.0
           AAPL                      0.05725                     0.0
           ABT                       0.05725                     0.0
           ACGL                      0.05725                     0.0

                   cpi_ema20_dev  nonfarm_payrolls_ema20_dev
Date       Ticker
2005-01-31 A           -0.036296                   19.376574
           AAP         -0.036296                   19.376574
           AAPL        -0.036296                   19.376574
           ABT         -0.036296                   19.376574
           ACGL        -0.036296                   19.376574

In [101]:
df = df.copy()

# Regression on Unwinsorized data giving near 0 R^2

### Below, we see that due to fat tails, the regression model does not work

In [102]:
import statsmodels.api as sm

# --- build regression dataset ---
reg_cols = ["fwd_ret_5"] + ema_dev_cols
reg_df   = df[reg_cols].dropna()

print(f"Regression rows: {len(reg_df):,}  |  Features: {len(ema_dev_cols)}")

y = reg_df["fwd_ret_5"]
X = sm.add_constant(reg_df[ema_dev_cols])

# --- OLS ---
# Use HC3 robust SEs — observations are not independent (same macro value
# appears across all tickers on a given date), so standard SEs are too small.
model  = sm.OLS(y, X).fit(cov_type="HC3")
print(model.summary())

# --- compact view: only significant predictors ---
results_df = pd.DataFrame({
    "coef"   : model.params,
    "pvalue" : model.pvalues,
    "tstat"  : model.tvalues,
}).drop("const").sort_values("pvalue")

print("\n=== Predictors sorted by p-value ===")
print(results_df.to_string())
print(f"\nR²: {model.rsquared:.6f}   Adj-R²: {model.rsquared_adj:.6f}")

Regression rows: 3,246,935  |  Features: 10
                            OLS Regression Results
==============================================================================
Dep. Variable:              fwd_ret_5   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     5.232
Date:                Tue, 19 May 2026   Prob (F-statistic):           3.78e-07
Time:                        19:18:43   Log-Likelihood:            -2.0930e+07
No. Observations:             3246935   AIC:                         4.186e+07
Df Residuals:                 3246925   BIC:                         4.186e+07
Df Model:                           9
Covariance Type:                  HC3
===============================================================================================
                                  coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
const                           1.8038      0.114     15.844      0.000       1.581       2.027
yield_10y_ema20_dev            -1.3589      0.671     -2.026      0.043      -2.674      -0.044
yield_2y_ema20_dev              2.2933      0.449      5.102      0.000       1.412       3.174
yield_curve_10y2y_ema20_dev    -3.6522      0.935     -3.905      0.000      -5.485      -1.819
yield_curve_10y3m_ema20_dev     0.1759      0.615      0.286      0.775      -1.029       1.381
fed_funds_rate_ema20_dev        0.0784      0.658      0.119      0.905      -1.212       1.369
vix_ema20_dev                   0.0115      0.030      0.380      0.704      -0.048       0.071
industrial_prod_ema20_dev       0.0853      0.097      0.878      0.380      -0.105       0.276
unemployment_ema20_dev         -0.7318      0.684     -1.070      0.284      -2.072       0.608
cpi_ema20_dev                  -1.0878      0.227     -4.790      0.000      -1.533      -0.643
nonfarm_payrolls_ema20_dev     -0.0003      0.000     -0.825      0.410      -0.001       0.000
==============================================================================
Omnibus:                 14258066.799   Durbin-Watson:                   2.000
Prob(Omnibus):                  0.000   Jarque-Bera (JB):   72853423451105.125
Skew:                         138.781   Prob(JB):                         0.00
Kurtosis:                   23206.994   Cond. No.                     3.19e+15
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The smallest eigenvalue is 1.37e-19. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

=== Predictors sorted by p-value ===
                                 coef        pvalue     tstat
yield_2y_ema20_dev           2.293289  3.354201e-07  5.102373
cpi_ema20_dev               -1.087769  1.663929e-06 -4.790468
yield_curve_10y2y_ema20_dev -3.652171  9.410720e-05 -3.905304
yield_10y_ema20_dev         -1.358881  4.281598e-02 -2.025501
unemployment_ema20_dev      -0.731797  2.844015e-01 -1.070484
industrial_prod_ema20_dev    0.085296  3.802040e-01  0.877520
nonfarm_payrolls_ema20_dev  -0.000287  4.095547e-01 -0.824677
vix_ema20_dev                0.011501  7.039980e-01  0.379929
yield_curve_10y3m_ema20_dev  0.175913  7.747338e-01  0.286188
fed_funds_rate_ema20_dev     0.078377  9.052425e-01  0.119042

R²: 0.000016   Adj-R²: 0.000013

/Users/pasqualebifulco/anaconda3/lib/python3.11/site-packages/statsmodels/base/model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 10, but rank is 9
  warnings.warn('covariance of constraints does not have full '

In [103]:
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

# ----------------------------------------------------------------------
# Drop-in replacement.
# Why: all 15 features are macro -> identical across tickers on a given
# date. The 3.1M-row panel is the same ~few-hundred macro observations
# repeated ~500x. The repetition adds no information; it just shrinks the
# standard errors to fiction. This collapses the panel to one row per
# date -- the time-series regression it actually is -- and uses
# Newey-West SEs to handle the autocorrelation from overlapping 5-day
# forward returns.
# ----------------------------------------------------------------------
df["date"] = df.index.get_level_values("Date")
DATE_COL    = "date"    # <-- set to your date column (or index name)
RET_OVERLAP = 5         # fwd_ret_5 overlaps 5 days -> Newey-West lag floor

reg_cols = ["fwd_ret_5"] + ema_dev_cols

# get date as a column whether it's currently the index or a column
work = df.reset_index() if DATE_COL not in df.columns else df.copy()

# tame fat tails in raw 5-day returns before aggregating
lo, hi = work["fwd_ret_5"].quantile([0.001, 0.995])
work["fwd_ret_5"] = work["fwd_ret_5"].clip(lo, hi)

# collapse panel -> one row per date.
# fwd_ret_5 becomes the equal-weighted cross-sectional mean return;
# the macro features are constant per date, so .mean() just recovers them.
daily = (work[[DATE_COL] + reg_cols]
         .dropna()
         .groupby(DATE_COL)
         .mean()
         .sort_index())

print(f"Panel rows: {len(work):,}  ->  daily rows: {len(daily):,}  "
      f"(this is your real sample size)")

y = daily["fwd_ret_5"]
X = sm.add_constant(daily[ema_dev_cols])

# Newey-West / HAC SEs: lag >= the return overlap to absorb the
# autocorrelation induced by overlapping 5-day windows.
maxlags = max(RET_OVERLAP, int(round(1.5 * RET_OVERLAP)))
model   = sm.OLS(y, X).fit(cov_type="HAC", cov_kwds={"maxlags": maxlags})
print(model.summary())

# --- collinearity check: the yield/curve features are near-redundant ---
vif = pd.DataFrame({
    "feature": ema_dev_cols,
    "VIF": [variance_inflation_factor(X.values, i + 1)   # +1 skips const
            for i in range(len(ema_dev_cols))],
}).sort_values("VIF", ascending=False)
print("\n=== VIF (>~10 = coefficient not interpretable; inf = drop it) ===")
print(vif.to_string(index=False))

# --- predictors sorted by p-value ---
results_df = (pd.DataFrame({
        "coef"  : model.params,
        "pvalue": model.pvalues,
        "tstat" : model.tvalues,
    })
    .drop("const")
    .sort_values("pvalue"))
print("\n=== Predictors sorted by p-value (HAC SEs) ===")
print(results_df.to_string())
print(f"\nR²: {model.rsquared:.6f}   Adj-R²: {model.rsquared_adj:.6f}")
print(f"N (days): {int(model.nobs)}   HAC maxlags: {maxlags}")

Panel rows: 3,260,173  ->  daily rows: 5,354  (this is your real sample size)
                            OLS Regression Results
==============================================================================
Dep. Variable:              fwd_ret_5   R-squared:                       0.018
Model:                            OLS   Adj. R-squared:                  0.017
Method:                 Least Squares   F-statistic:                     2.889
Date:                Tue, 19 May 2026   Prob (F-statistic):            0.00208
Time:                        19:18:44   Log-Likelihood:                 11770.
No. Observations:                5354   AIC:                        -2.352e+04
Df Residuals:                    5344   BIC:                        -2.345e+04
Df Model:                           9
Covariance Type:                  HAC
===============================================================================================
                                  coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
const                           0.0033      0.001      3.888      0.000       0.002       0.005
yield_10y_ema20_dev             0.0045      0.012      0.366      0.715      -0.020       0.029
yield_2y_ema20_dev              0.0043      0.007      0.589      0.556      -0.010       0.019
yield_curve_10y2y_ema20_dev     0.0002      0.011      0.017      0.986      -0.021       0.021
yield_curve_10y3m_ema20_dev    -0.0234      0.015     -1.534      0.125      -0.053       0.007
fed_funds_rate_ema20_dev       -0.0074      0.016     -0.451      0.652      -0.039       0.025
vix_ema20_dev                  -0.0001      0.000     -0.283      0.777      -0.001       0.001
industrial_prod_ema20_dev      -0.0007      0.001     -0.728      0.466      -0.003       0.001
unemployment_ema20_dev         -0.0110      0.006     -1.809      0.070      -0.023       0.001
cpi_ema20_dev                  -0.0015      0.002     -0.897      0.370      -0.005       0.002
nonfarm_payrolls_ema20_dev  -8.041e-06   3.15e-06     -2.549      0.011   -1.42e-05   -1.86e-06
==============================================================================
Omnibus:                     1153.595   Durbin-Watson:                   0.446
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            10744.065
Skew:                          -0.761   Prob(JB):                         0.00
Kurtosis:                       9.771   Cond. No.                     9.14e+17
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity and autocorrelation robust (HAC) using 8 lags and without small sample correction
[2] The smallest eigenvalue is 2.63e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

=== VIF (>~10 = coefficient not interpretable; inf = drop it) ===
                    feature       VIF
        yield_10y_ema20_dev       inf
         yield_2y_ema20_dev       inf
yield_curve_10y2y_ema20_dev       inf
 nonfarm_payrolls_ema20_dev 10.986980
     unemployment_ema20_dev 10.865161
yield_curve_10y3m_ema20_dev  2.834170
   fed_funds_rate_ema20_dev  1.287359
  industrial_prod_ema20_dev  1.151825
              vix_ema20_dev  1.112567
              cpi_ema20_dev  1.099437

=== Predictors sorted by p-value (HAC SEs) ===
                                 coef    pvalue     tstat
nonfarm_payrolls_ema20_dev  -0.000008  0.010802 -2.549052
unemployment_ema20_dev      -0.010968  0.070419 -1.809208
yield_curve_10y3m_ema20_dev -0.023406  0.125091 -1.533751
cpi_ema20_dev               -0.001455  0.369743 -0.896956
industrial_prod_ema20_dev   -0.000696  0.466405 -0.728341
yield_2y_ema20_dev           0.004316  0.555646  0.589321
fed_funds_rate_ema20_dev    -0.007351  0.651744 -0.451341
yield_10y_ema20_dev          0.004497  0.714501  0.365818
vix_ema20_dev               -0.000120  0.776993 -0.283240
yield_curve_10y2y_ema20_dev  0.000181  0.986353  0.017104

R²: 0.018356   Adj-R²: 0.016703
N (days): 5354   HAC maxlags: 8

/Users/pasqualebifulco/anaconda3/lib/python3.11/site-packages/statsmodels/base/model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 10, but rank is 9
  warnings.warn('covariance of constraints does not have full '
/Users/pasqualebifulco/anaconda3/lib/python3.11/site-packages/statsmodels/stats/outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

Directional accuracy + signal/return correlation.

`signal` = the model's linear prediction, DEMEANED: the intercept is
constant and carries zero timing information, so |signal| is only
meaningful relative to the signal's own mean. Both series are demeaned,
so 50% directional accuracy = no skill.

In [104]:
import numpy as np

signal = model.fittedvalues - model.fittedvalues.mean()   # demeaned prediction
actual = y - y.mean()                                      # demeaned return
sd_sig = signal.std()

# correlation of realized return with signal (invariant to demeaning).
# for an IN-SAMPLE OLS fit this is mechanically sqrt(R^2) -- redundant here;
# it only becomes independent information for OOS predictions.
corr = np.corrcoef(y, model.fittedvalues)[0, 1]
print(f"corr(actual, signal): {corr:+.4f}   "
      f"(in-sample = sqrt(R^2) = {np.sqrt(model.rsquared):.4f})\n")

# directional accuracy at increasing signal-strength thresholds.
# 50% = coin flip. A real signal -> dir_acc rises as the threshold rises.
hdr = f"{'threshold':>12}{'n_obs':>9}{'kept':>8}{'dir_acc':>10}{'+-SE':>8}"
print(hdr); print('-' * len(hdr))
for n in (0, 1, 2, 3):
    mask = signal.abs() > n * sd_sig
    k = int(mask.sum())
    if k == 0:
        print(f"{f'|sig|>{n}sd':>12}{0:>9}{'--':>8}{'--':>10}{'--':>8}")
        continue
    hit = (np.sign(signal[mask]) == np.sign(actual[mask])).mean()
    se  = np.sqrt(hit * (1 - hit) / k)        # binomial SE -- see caveat below
    print(f"{f'|sig|>{n}sd':>12}{k:>9}{k/len(signal)*100:>7.1f}%"
          f"{hit*100:>9.1f}%{se*100:>7.1f}%")

corr(actual, signal): +0.1355   (in-sample = sqrt(R^2) = 0.1355)

   threshold    n_obs    kept   dir_acc    +-SE
-----------------------------------------------
   |sig|>0sd     5354  100.0%     50.7%    0.7%
   |sig|>1sd      829   15.5%     56.6%    1.7%
   |sig|>2sd      181    3.4%     68.5%    3.5%
   |sig|>3sd       80    1.5%     77.5%    4.7%

In [105]:
import numpy as np
from pathlib import Path

# ─── Load & featurize Form 4 data ────────────────────────────────────────────

# 1. Load all available CSVs
form4_files = sorted(Path("form4_data").glob("form4_*.csv"))
print(f"Loading {len(form4_files)} Form 4 files...")
form4_raw = pd.concat([pd.read_csv(f) for f in form4_files], ignore_index=True)
print(f"Total raw transactions: {len(form4_raw):,}")

# 2. Filter to open-market buys (P) and sales (S) only
#    Exclude: M (option exercise), F (tax withholding), G (gift), A (grant)
form4_raw["filing_date"] = pd.to_datetime(form4_raw["filing_date"]).dt.normalize()
form4_raw["Shares"] = pd.to_numeric(form4_raw["Shares"], errors="coerce")
form4_raw["Value"]  = pd.to_numeric(form4_raw["Value"],  errors="coerce")

open_mkt = form4_raw[form4_raw["Code"].isin(["P", "S"])].copy()
sign = open_mkt["Code"].map({"P": 1, "S": -1})
open_mkt["signed_shares"] = open_mkt["Shares"] * sign
open_mkt["signed_value"]  = open_mkt["Value"]  * sign

# 3. Aggregate to (filing_date, ticker): net buys/sells per filing day
f4_daily = (
    open_mkt
    .groupby(["filing_date", "query_ticker"])
    .agg(
        net_shares=("signed_shares", "sum"),
        net_value =("signed_value",  "sum"),
        buy_count =("Code", lambda x: (x == "P").sum()),
        sell_count=("Code", lambda x: (x == "S").sum()),
    )
    .reset_index()
    .rename(columns={"query_ticker": "Ticker"})
)
print(f"Filing events: {len(f4_daily):,}  |  Tickers: {f4_daily['Ticker'].nunique()}")

# 4. PIT shift: filing on day D → available next trading session (D+1)
trading_dates = df.index.get_level_values("Date").unique().sort_values()
td_arr = trading_dates.values
filing_arr = f4_daily["filing_date"].values
idx = np.searchsorted(td_arr, filing_arr, side="right")   # first date strictly after filing
valid = idx < len(td_arr)
f4_daily = f4_daily[valid].copy()
f4_daily["avail_date"] = pd.DatetimeIndex(td_arr[idx[valid]])

# 5. Set MultiIndex, collapse same (avail_date, ticker) duplicates
f4_cols = ["net_shares", "net_value", "buy_count", "sell_count"]
f4_mi = (
    f4_daily.set_index(["avail_date", "Ticker"])[f4_cols]
    .rename_axis(["Date", "Ticker"])
    .groupby(level=["Date", "Ticker"]).sum()
)

# 6. Expand to full (trading_dates × form4 tickers) grid, 0 on silent days
f4_tickers = f4_mi.index.get_level_values("Ticker").unique()
full_idx   = pd.MultiIndex.from_product([trading_dates, f4_tickers], names=["Date", "Ticker"])
f4_full    = f4_mi.reindex(full_idx, fill_value=0).sort_index()

# 7. Rolling 20-session cumulative sum per ticker
#    Unstack → rolling on date axis (naturally per-ticker column) → stack back
ROLL_WINDOW = 20
f4_wide   = f4_full.unstack("Ticker")
roll_wide = f4_wide.rolling(window=ROLL_WINDOW, min_periods=1).sum()
roll_f4   = roll_wide.stack("Ticker")[f4_cols].sort_index()
roll_f4.columns = [f"insider_{c}_roll{ROLL_WINDOW}" for c in f4_cols]
roll_f4.index.names = ["Date", "Ticker"]

print(f"Insider feature grid: {roll_f4.shape}  (dates × tickers with form4 data)")

# 8. Join to main panel (NaN for tickers with no form4 data)
for col in roll_f4.columns:
    df[col] = roll_f4[col]

print(f"Panel shape after Form 4 join: {df.shape}")
df[[c for c in df.columns if c.startswith("insider_")]].describe()

Loading 1 Form 4 files...
Total raw transactions: 1
Filing events: 1  |  Tickers: 1
Insider feature grid: (5378, 4)  (dates × tickers with form4 data)
Panel shape after Form 4 join: (3260173, 36)

,insider_net_shares_roll20,insider_net_value_roll20,insider_buy_count_roll20,insider_sell_count_roll20
count,5378.0,5378.0,5378.000000,5378.0
mean,0.0,0.0,0.003719,0.0
std,0.0,0.0,0.060875,0.0
min,0.0,0.0,0.000000,0.0
25%,0.0,0.0,0.000000,0.0
50%,0.0,0.0,0.000000,0.0
75%,0.0,0.0,0.000000,0.0
max,0.0,0.0,1.000000,0.0